# MONGODB SETTING
MONGO_HOST = 'localhost'
MONGO_PORT = 27017
MONGO_USERNAME = None
MONGO_PASSWORD = None
MONGO_DATABASE = 'Test_d'
MONGO_COLLECTION = 'Test_c'
MONGO_CONN_TIMEOUT = 30
MONGO_CONN_RETRIES = 5


# MYSQL SETTING
MYSQL_HOST = 'localhost'
MYSQL_PORT = 3306
MYSQL_USERNAME = None
MYSQL_PASSWORD = None
MYSQL_DATABASE = 'Test_d'
MYSQL_COLLECTION = 'Test_c'
MYSQL_CONN_TIMEOUT = 30
MYSQL_CONN_RETRIES = 5
MYSQL_ = None